version: '3'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data

  kafka:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: 127.0.0.1
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: 'true'
    ports:
      - '2181:2181'
      - '9092:9092'
